# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd591144c861cecc2fc5ce80d0c802b3054d9a9c7030649fdd29e3838a5ee0fed175cf8074b1d10ac9daec6b27ddb348984f21335d658387ff00fbf2ce2d6d3e

test:
  secret_key_base: 046675d24a808e9a9f45c40177a0d481411d50c64a70479dd9723acaf07d26bc50b141bbab735b30499d25aba4b9411a4d08b69d0bc4cc813ed1ab3e6f9575ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
